### ISSUE TITLE
Move From MongoDB to SQLAlchemy

### ISSUE THREAD

**Issue by cganas** [picoCTF/picoCTF-Platform-2#17]
We haven't been using MongoDB correctly which has resulted in a relational nosql database with race conditions. Most of our data is relational so SQLAlchemy would be more appropriate. We successfully limited the numbers of call the API makes directly to the database so external tools such as the API manager should not be affected.

This enhancement is non-trivial but should not be a huge time sink. I will be making the changes incrementally, leaving the mongo code around until we are ready to make the full switch.

I've created a branch here. https://github.com/picoCTF/picoCTF-Platform-2/tree/sql_alchemy

**Comment by GroundPound** [comment]
I understand restructuring how we use Mongo but I don't really see the reason to switch to SQL. It strikes me as unnecessary work. Given the choice between fixing the handful of poor design decisions that cause the race conditions and completely moving to a new technology, I don't quite understand why wouldn't just fix what we have. Regarding the natural organization of data, the question isn't so much is it relational (of course a relational schema could represent this) but is the data non-hierarchical.

**Comment by cganas** [comment]
The design decisions we made were only poor because we were using Mongo. SQLAlchemy gives a lot more control as far as rollback and transactions. A prime example is that with SQLAlchemy we can create a database session whenever we begin a user creation request. The newly created team and user are only committed to the database whenever we finish. Our current model doesn't support transactions so when something goes wrong we face synchronization issues like having a team without any users because user registration failed.

I know it's not obvious as to why this is a great use of time but I think it's at least an important thing to investigate. If anything, this might be the best way to evaluate whether or not it's worth the time.

**Comment by GroundPound** [comment]
The team-users example was done poorly because the code and schema ignored the underlying technology. In that example users are in a many to one relationship with a team and should be placed under a team where Mongo gives you the guarantees you need to do that update safely. That is a relationship that is hierarchical under a team. If we prefer to have general purpose transactions so that developers do not have to think about the database limitations and just wrap everything in a transaction then I guess I see this as an improvement.

**Comment by dbrumley** [comment]
In part it seems like we should re-evaluate how much user management we code ourself, as opposed to using existing code.  This may be a separate feature request, though.

**Comment by cganas** [comment]
I'll be using this in part to make notes and keep track of what needs done:

## Todo
- [x] Add User classes, Group, and Team models with relationships
- [x] Differentiate between Teachers and Competitors (later Admins)
- [ ] Convert existing API calls removing Mongo
  - [ ] User
  - [ ] Group
  - [ ] Team
- [ ] Add teacher submodule and registration
- [ ] Modify registration to use different creation endpoints
- [ ] Modify registration tests to reflect these changes

### Notes

Additional thought needs to go into the representation of achievements and problems.

**Comment by GroundPound** [comment]
It's been about two months since that the SQL Alchemy branch was updated. Is this still an ongoing project?

**Comment by cganas** [comment]
There has been significant progress under the sql_alchemy branch; however, I was unable to dedicate enough time to it during the semester to finish it. I would be able to finish it now, during the summer, but I don't know that it has been given sufficient priority from work to take focus at the moment.

**Comment by GroundPound** [comment]
Priority from work? I'm not sure I follow.

**Comment by cganas** [comment]
That came out very confusing. It isn't dead, I just don't know when I'll be able to pick it back up. If someone wants to work on it I would be happy to explain in more detail.

**Comment by GroundPound** [comment]
Alright, for now I'm going to unassign you. Feel free to take it back when you plan to pick it up again! I still maintain this is a low-priority overhaul, and outside of your work priorities, effort is better put elsewhere in the project.

**Comment by royragsdale** [comment]
Closed as a legacy enhancement and development shifting to [picoCTF-platform](https://github.com/picoCTF/picoCTF-platform)
